general:
  magicaltool: 58
  use_worldguard: true
  use_logblock: true
  debug: false
blocks:
  logs: true
  stairs: true
  pistons: false
  chests: true
  slabs: true
  diodes: true
  hoppers: true